# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# Set update schedule for GitHub actions and other package managers

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions-versions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: sunday
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      backend-versions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /test-resources
    schedule:
      interval: weekly
      day: sunday
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      backend-versions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
