AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scheduled Lambda Function with esbuild Build

Resources:
  FindAvailableSlotsFunction:
    Type: 'AWS::Serverless::Function'
    
    # Metadata for SAM build process
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2022' 
        EntryPoints: 
          - src/functions/findAvailableSlotsHandler.ts

    # Standard Lambda function Properties
    Properties: 
      Runtime: nodejs20.x
      Handler: src/functions/findAvailableSlotsHandler.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)' 