name: Backend Pre-Merge
on:
  # Triggers the workflow on pull request events for all branches
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-pre-merge.yml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    name: Run CI checks
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup nodeJS v22
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: backend/.nvmrc
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm clean-install

      - name: Linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Install rain
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install rain

      - name: Check infra formatting
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          npm run infra:format:check

      - name: Run infra tests
        run: npm run test:infra

      - name: Run unit tests
        run: npm run test:unit

      - name: Validate SAM template
        run: sam validate --lint

      - name: Validate SAM build
        run: sam build --parallel

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@555b1fe117f21ed74b66d7d0182824d382e3c5ef # v12.3045.0
        with:
          file: /backend/template.yaml
          output_format: cli,sarif
          output_file_path: console,results.sarif
          framework: cloudformation

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@4e828ff8d448a8a6e532957b1811f387a63867e8 # v3.29.4
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: backend

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: backend/.scannerwork/report-task.txt
